### ISSUE TITLE
io.bit3.jsass.adapter.NativeLoader - Platform windows 7:amd64 not supported

### ISSUE THREAD

**Issue by aniketkudale** [bit3/jsass#38]
why amd64 is not supported?

```
[main] WARN io.bit3.jsass.adapter.NativeLoader - Platform windows 7:amd64 not supported
java.lang.UnsupportedOperationException: Platform windows 7:amd64 not supported
    at io.bit3.jsass.adapter.NativeLoader.unsupportedPlatform(NativeLoader.java:184)
    at io.bit3.jsass.adapter.NativeLoader.findLibraryResource(NativeLoader.java:68)
    at io.bit3.jsass.adapter.NativeLoader.saveLibrary(NativeLoader.java:167)
    at io.bit3.jsass.adapter.NativeLoader.loadLibrary(NativeLoader.java:34)
    at io.bit3.jsass.adapter.NativeAdapter.<clinit>(NativeAdapter.java:28)
    at io.bit3.jsass.Compiler.<init>(Compiler.java:32)
    at CompileFileExample.main(CompileFileExample.java:17)
Exception in thread "main" java.lang.ExceptionInInitializerError
    at io.bit3.jsass.Compiler.<init>(Compiler.java:32)
    at CompileFileExample.main(CompileFileExample.java:17)
Caused by: io.bit3.jsass.adapter.LoaderException: java.lang.UnsupportedOperationException: Platform windows 7:amd64 not supported
    at io.bit3.jsass.adapter.NativeLoader.loadLibrary(NativeLoader.java:40)
    at io.bit3.jsass.adapter.NativeAdapter.<clinit>(NativeAdapter.java:28)
    ... 2 more
Caused by: java.lang.UnsupportedOperationException: Platform windows 7:amd64 not supported
    at io.bit3.jsass.adapter.NativeLoader.unsupportedPlatform(NativeLoader.java:184)
    at io.bit3.jsass.adapter.NativeLoader.findLibraryResource(NativeLoader.java:68)
    at io.bit3.jsass.adapter.NativeLoader.saveLibrary(NativeLoader.java:167)
    at io.bit3.jsass.adapter.NativeLoader.loadLibrary(NativeLoader.java:34)
    ... 3 more
```

**Comment by tristanlins** [comment]
Windows+amd64 is supportet, see https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/adapter/NativeLoader.java#L99
Are you using the latest version of jsass?

**Comment by aniketkudale** [comment]
Yes, I am using latest version of jsass! Still getting this `UnsupportedOperationException`!

**Comment by tristanlins** [comment]
It seems that [`NativeLoader.class.getResource(resourceName)`](https://github.com/bit3/jsass/blob/5.1.1/src/main/java/io/bit3/jsass/adapter/NativeLoader.java#L65) does not find the DLL. Please add the resourceName to the exception at line 68 like this: [unsupportedPlatform(osName, osArch + " " + resourceName);](https://github.com/bit3/jsass/blob/5.1.1/src/main/java/io/bit3/jsass/adapter/NativeLoader.java#L68) just for testing purpose?!

**Comment by tristanlins** [comment]
I have improved the exception handling a bit.
Until this error occurs again, I close this issue.
Feel free to open a new one, if it is still failing.
